//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work_Apl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APLFileItem
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string FileSize { get; set; }
    }
}
